### ISSUE TITLE
Request for the Revised Text Annotations of QaTa-COV19 Dataset

### ISSUE THREAD

**Issue by liruiyangsu** [nguyenpbui/MMI-UNet#2]
Hi,Thank you for sharing the code and resources for your impressive work. I am currently working on related research and am particularly interested in the revised text annotations of the QaTa-COV19 Dataset mentioned in your paper. However, I could not find this updated version in the repository. Could you please let me know where I can access the revised text annotations or provide any guidance on obtaining them? Thank you so much for your time and assistance!

**Comment by nguyenpbui** [comment]
Hi @liruiyangsu,

Thank you for your interest in our work. Please find the downloadl linkn for text annotations of the QaTa-COV19 dataset in the following link: https://github.com/HUANGLIZI/LViT
